More flexibility

diff --git a/.github/workflows/release-advanced.yml b/.github/workflows/release-advanced.yml
--- a/.github/workflows/release-advanced.yml
+++ b/.github/workflows/release-advanced.yml
@@ -17,12 +17,15 @@ env:
   PACKAGE_LICENSE_FILE: "LICENSE"
   PACKAGE_KEYWORDS: "Toon, Shader, Material"
   PACKAGE_LEGACYFOLDERS: "Assets\\lilToonMore: , Assets\\lilToonMore Advanced:"
+  FAIL_VERIFICATION_FAILED: 1
 jobs:
   verify-commit-signature:
     runs-on: ubuntu-latest
     defaults:
       run:
         shell: bash
+    outputs:
+      vcs: ${{ steps.verify_step.outputs.vcs }}
     steps:
       - uses: actions/checkout@v6
         with:
@@ -31,6 +34,7 @@ jobs:
         run: |
           echo "${{ secrets.GPG_PUBLIC_KEY }}" | gpg --import
       - name: Verify Commit Signature
+        id: verify_step
         run: |
           FILE_PATH="update_trigger.json"
           CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)
@@ -46,11 +50,19 @@ jobs:
           echo "$LOG_OUTPUT"
           
           if echo "$LOG_OUTPUT" | grep -q "gpg: Good signature"; then
+            verify="The signature of the triggering commit has been verified, so it should be safe."
+            echo "vcs=$verify" >> "$GITHUB_OUTPUT"
             echo "✅ Commit signature verification successful"
           else
-            echo "❌ Error: Terminated"
-            echo "Reason: Commit signature verification failed"
-            exit 1
+            if ${{ env.FAIL_VERIFICATION_FAILED }}; then
+              echo "❌ Error: Terminated"
+              echo "Reason: Commit signature verification failed"
+              exit 1
+            else
+              verify="The signature of the triggering commit has not been verified and may be insecure"
+              echo "vcs=$verify" >> "$GITHUB_OUTPUT"
+              echo "⚠️ Warning: Commit signature verification failed"
+            fi
           fi
   extract-semantic-version:
     runs-on: ubuntu-latest
@@ -138,8 +150,9 @@ jobs:
     defaults:
       run:
         shell: bash
-    needs: extract-semantic-version
+    needs: [verify-commit-signature, extract-semantic-version]
     env:
+      VCS: ${{ needs.verify-commit-signature.outputs.vcs }}
       CURRENT_VERSION: ${{ needs.extract-semantic-version.outputs.current_version }}
       MAJOR: ${{ needs.extract-semantic-version.outputs.major }}
       MINOR: ${{ needs.extract-semantic-version.outputs.minor }}
@@ -220,7 +233,11 @@ jobs:
         with:
           fail_on_self_push: false
           branch: master
-          commit_message: "Updated Ver. ${{ env.UPDATE_VERSION }}"
+          commit_message: |
+            Updated Ver. ${{ env.UPDATE_VERSION }}
+            
+            - Automatically generated by GitHub Actions.
+            - Security Check: ${{ env.VCS }}
   release:
     permissions:
       contents: write
